# This code was automatically generated by CWrap version 0.0.0

cdef extern from "NBioAPI.h":

    ctypedef signed char NBioAPI_SINT8

    ctypedef unsigned char NBioAPI_UINT8

    ctypedef short NBioAPI_SINT16

    ctypedef unsigned short NBioAPI_UINT16

    ctypedef int NBioAPI_SINT32

    ctypedef unsigned int NBioAPI_UINT32

    ctypedef long long NBioAPI_SINT64

    ctypedef unsigned long long NBioAPI_UINT64

    ctypedef long NBioAPI_SLONG

    ctypedef unsigned long NBioAPI_ULONG

    ctypedef double NBioAPI_DOUBLE

    ctypedef float NBioAPI_FLOAT

    ctypedef int NBioAPI_SINT

    ctypedef unsigned int NBioAPI_UINT

    ctypedef int NBioAPI_BOOL

    ctypedef char NBioAPI_CHAR

    ctypedef int NBioAPI_WCHAR

    ctypedef unsigned char NBioAPI_BYTE

    ctypedef NBioAPI_CHAR *NBioAPI_CHAR_PTR

    ctypedef NBioAPI_WCHAR *NBioAPI_WCHAR_PTR

    ctypedef NBioAPI_BYTE *NBioAPI_BYTE_PTR

    ctypedef NBioAPI_CHAR_PTR LPSTR

    ctypedef NBioAPI_CHAR CHAR

    ctypedef void *HINSTANCE

    ctypedef NBioAPI_UINT32 NBioAPI_HWND

    ctypedef void *NBioAPI_VOID_PTR

    ctypedef NBioAPI_UINT16 NBioAPI_FIR_VERSION

    cdef struct nbioapi_version:
        NBioAPI_UINT32 Major
        NBioAPI_UINT32 Minor

    ctypedef nbioapi_version NBioAPI_VERSION

    ctypedef nbioapi_version *NBioAPI_VERSION_PTR

    ctypedef NBioAPI_UINT16 NBioAPI_FIR_DATA_TYPE

    ctypedef NBioAPI_UINT16 NBioAPI_FIR_PURPOSE

    ctypedef NBioAPI_UINT16 NBioAPI_FIR_QUALITY

    cdef struct nbioapi_fir_header:
        NBioAPI_UINT32 Length
        NBioAPI_UINT32 DataLength
        NBioAPI_FIR_VERSION Version
        NBioAPI_FIR_DATA_TYPE DataType
        NBioAPI_FIR_PURPOSE Purpose
        NBioAPI_FIR_QUALITY Quality
        NBioAPI_UINT32 Reserved

    ctypedef nbioapi_fir_header NBioAPI_FIR_HEADER

    ctypedef nbioapi_fir_header *NBioAPI_FIR_HEADER_PTR

    ctypedef NBioAPI_UINT8 NBioAPI_FIR_DATA

    ctypedef NBioAPI_UINT32 NBioAPI_FIR_FORMAT

    cdef struct nbioapi_fir:
        NBioAPI_FIR_FORMAT Format
        NBioAPI_FIR_HEADER Header
        NBioAPI_FIR_DATA *Data

    ctypedef nbioapi_fir NBioAPI_FIR

    ctypedef nbioapi_fir *NBioAPI_FIR_PTR

    cdef struct nbioapi_fir_payload:
        NBioAPI_UINT32 Length
        NBioAPI_UINT8 *Data

    ctypedef nbioapi_fir_payload NBioAPI_FIR_PAYLOAD

    ctypedef nbioapi_fir_payload *NBioAPI_FIR_PAYLOAD_PTR

    ctypedef NBioAPI_UINT NBioAPI_HANDLE

    ctypedef NBioAPI_UINT *NBioAPI_HANDLE_PTR

    ctypedef NBioAPI_UINT NBioAPI_FIR_HANDLE

    ctypedef NBioAPI_UINT *NBioAPI_FIR_HANDLE_PTR

    ctypedef NBioAPI_UINT32 NBioAPI_FIR_SECURITY_LEVEL

    cdef struct nbioapi_init_info_0:
        NBioAPI_UINT32 StructureType
        NBioAPI_UINT32 MaxFingersForEnroll
        NBioAPI_UINT32 SamplesPerFinger
        NBioAPI_UINT32 DefaultTimeout
        NBioAPI_UINT32 EnrollImageQuality
        NBioAPI_UINT32 VerifyImageQuality
        NBioAPI_UINT32 IdentifyImageQuality
        NBioAPI_FIR_SECURITY_LEVEL SecurityLevel

    ctypedef nbioapi_init_info_0 NBioAPI_INIT_INFO_0

    ctypedef nbioapi_init_info_0 *NBioAPI_INIT_INFO_PTR_0

    cdef struct nbioapi_init_info_1:
        NBioAPI_UINT32 StructureType
        NBioAPI_FIR_SECURITY_LEVEL SecurityLevelForEnroll
        NBioAPI_UINT32 NecessaryEnrollNum
        NBioAPI_UINT32 Reserved1
        NBioAPI_UINT32 Reserved2
        NBioAPI_UINT32 Reserved3
        NBioAPI_UINT32 Reserved4
        NBioAPI_UINT32 Reserved5
        NBioAPI_UINT32 Reserved6
        NBioAPI_UINT32 Reserved7

    ctypedef nbioapi_init_info_1 NBioAPI_INIT_INFO_1

    ctypedef nbioapi_init_info_1 *NBioAPI_INIT_INFO_PTR_1

    ctypedef NBioAPI_VOID_PTR NBioAPI_INIT_INFO_PTR

    cdef struct nbioapi_device_info_0:
        NBioAPI_UINT32 StructureType
        NBioAPI_UINT32 ImageWidth
        NBioAPI_UINT32 ImageHeight
        NBioAPI_UINT32 Brightness
        NBioAPI_UINT32 Contrast
        NBioAPI_UINT32 Gain

    ctypedef nbioapi_device_info_0 NBioAPI_DEVICE_INFO_0

    ctypedef nbioapi_device_info_0 *NBioAPI_DEVICE_INFO_PTR_0

    ctypedef NBioAPI_VOID_PTR NBioAPI_DEVICE_INFO_PTR

    ctypedef NBioAPI_UINT16 NBioAPI_DEVICE_ID

    ctypedef NBioAPI_UINT8 NBioAPI_DEVICE_NAME

    ctypedef NBioAPI_UINT32 NBioAPI_RETURN

    cdef struct nbioapi_fir_textencode:
        NBioAPI_BOOL IsWideChar
        NBioAPI_CHAR_PTR TextFIR

    ctypedef nbioapi_fir_textencode NBioAPI_FIR_TEXTENCODE

    ctypedef nbioapi_fir_textencode *NBioAPI_FIR_TEXTENCODE_PTR

    ctypedef NBioAPI_UINT8 NBioAPI_INPUT_FIR_FORM

    cdef union __nbioapi_input_fir_InputFIR:
        NBioAPI_FIR_HANDLE_PTR FIRinBSP
        NBioAPI_VOID_PTR FIR
        NBioAPI_FIR_TEXTENCODE_PTR TextFIR

    ctypedef __nbioapi_input_fir_InputFIR __nbioapi_input_fir_InputFIR_t

    cdef struct nbioapi_input_fir:
        NBioAPI_INPUT_FIR_FORM Form
        __nbioapi_input_fir_InputFIR_t InputFIR

    ctypedef nbioapi_input_fir NBioAPI_INPUT_FIR

    ctypedef nbioapi_input_fir *NBioAPI_INPUT_FIR_PTR

    ctypedef NBioAPI_UINT32 NBioAPI_WINDOW_STYLE

    cdef struct nbioapi_window_callback_param_ex:
        NBioAPI_UINT32 dwDeviceError
        NBioAPI_UINT32 dwReserved[8]
        NBioAPI_VOID_PTR lpReserved

    ctypedef nbioapi_window_callback_param_ex NBioAPI_WINDOW_CALLBACK_PARAM_EX

    ctypedef nbioapi_window_callback_param_ex *NBioAPI_WINDOW_CALLBACK_PARAM_PTR_EX

    cdef struct nbioapi_window_callback_param_0:
        NBioAPI_UINT32 dwQuality
        NBioAPI_UINT8 *lpImageBuf
        NBioAPI_WINDOW_CALLBACK_PARAM_PTR_EX pParamEx

    ctypedef nbioapi_window_callback_param_0 NBioAPI_WINDOW_CALLBACK_PARAM_0

    ctypedef nbioapi_window_callback_param_0 *NBioAPI_WINDOW_CALLBACK_PARAM_PTR_0

    cdef struct nbioapi_window_callback_param_1_1:
        NBioAPI_UINT32 dwStartTime
        NBioAPI_UINT32 dwCapTime
        NBioAPI_UINT32 dwEndTime
        NBioAPI_UINT32 Reserved1
        NBioAPI_UINT32 Reserved2
        NBioAPI_UINT32 Reserved3
        NBioAPI_UINT32 Reserved4
        NBioAPI_UINT32 Reserved5
        NBioAPI_UINT32 Reserved6
        NBioAPI_UINT32 Reserved7
        NBioAPI_UINT32 Reserved8
        NBioAPI_VOID_PTR lpReserved

    ctypedef nbioapi_window_callback_param_1_1 NBioAPI_WINDOW_CALLBACK_PARAM_1_1

    ctypedef nbioapi_window_callback_param_1_1 *NBioAPI_WINDOW_CALLBACK_PARAM_PTR_1_1

    cdef struct nbioapi_window_callback_param_1:
        NBioAPI_UINT32 dwResult
        NBioAPI_WINDOW_CALLBACK_PARAM_PTR_1_1 lpCBParam1_1

    ctypedef nbioapi_window_callback_param_1 NBioAPI_WINDOW_CALLBACK_PARAM_1

    ctypedef nbioapi_window_callback_param_1 *NBioAPI_WINDOW_CALLBACK_PARAM_PTR_1

    ctypedef unsigned int (*NBioAPI_WINDOW_CALLBACK_0)(nbioapi_window_callback_param_0 *, void *)

    ctypedef unsigned int (*NBioAPI_WINDOW_CALLBACK_1)(nbioapi_window_callback_param_1 *, void *)

    cdef struct nbioapi_callback_info_0:
        NBioAPI_UINT32 CallBackType
        NBioAPI_WINDOW_CALLBACK_0 CallBackFunction
        NBioAPI_VOID_PTR UserCallBackParam

    ctypedef nbioapi_callback_info_0 NBioAPI_CALLBACK_INFO_0

    ctypedef nbioapi_callback_info_0 *NBioAPI_CALLBACK_INFO_PTR_0

    cdef struct nbioapi_callback_info_1:
        NBioAPI_UINT32 CallBackType
        NBioAPI_WINDOW_CALLBACK_1 CallBackFunction
        NBioAPI_VOID_PTR UserCallBackParam

    ctypedef nbioapi_callback_info_1 NBioAPI_CALLBACK_INFO_1

    ctypedef nbioapi_callback_info_1 *NBioAPI_CALLBACK_INFO_PTR_1

    cdef struct nbioapi_window_option_2:
        NBioAPI_UINT8 FPForeColor[3]
        NBioAPI_UINT8 FPBackColor[3]
        NBioAPI_UINT8 DisableFingerForEnroll[10]
        NBioAPI_UINT32 Reserved1[4]
        NBioAPI_VOID_PTR Reserved2

    ctypedef nbioapi_window_option_2 NBioAPI_WINDOW_OPTION_2

    ctypedef nbioapi_window_option_2 *NBioAPI_WINDOW_OPTION_PTR_2

    cdef struct nbioapi_window_option:
        NBioAPI_UINT32 Length
        NBioAPI_WINDOW_STYLE WindowStyle
        NBioAPI_HWND ParentWnd
        NBioAPI_HWND FingerWnd
        NBioAPI_CALLBACK_INFO_0 CaptureCallBackInfo
        NBioAPI_CALLBACK_INFO_1 FinishCallBackInfo
        NBioAPI_CHAR_PTR CaptionMsg
        NBioAPI_CHAR_PTR CancelMsg
        NBioAPI_WINDOW_OPTION_PTR_2 Option2

    ctypedef nbioapi_window_option NBioAPI_WINDOW_OPTION

    ctypedef nbioapi_window_option *NBioAPI_WINDOW_OPTION_PTR

    cdef enum MINCONV_DATA_TYPE:
        MINCONV_TYPE_FDP
        MINCONV_TYPE_FDU
        MINCONV_TYPE_FDA
        MINCONV_TYPE_OLD_FDA
        MINCONV_TYPE_FDAC
        MINCONV_TYPE_FIM10_HV
        MINCONV_TYPE_FIM10_LV
        MINCONV_TYPE_FIM01_HV
        MINCONV_TYPE_FIM01_HD
        MINCONV_TYPE_FELICA
        MINCONV_TYPE_EXTENSION
        MINCONV_TYPE_TEMPLATESIZE_32
        MINCONV_TYPE_TEMPLATESIZE_48
        MINCONV_TYPE_TEMPLATESIZE_64
        MINCONV_TYPE_TEMPLATESIZE_80
        MINCONV_TYPE_TEMPLATESIZE_96
        MINCONV_TYPE_TEMPLATESIZE_112
        MINCONV_TYPE_TEMPLATESIZE_128
        MINCONV_TYPE_TEMPLATESIZE_144
        MINCONV_TYPE_TEMPLATESIZE_160
        MINCONV_TYPE_TEMPLATESIZE_176
        MINCONV_TYPE_TEMPLATESIZE_192
        MINCONV_TYPE_TEMPLATESIZE_208
        MINCONV_TYPE_TEMPLATESIZE_224
        MINCONV_TYPE_TEMPLATESIZE_240
        MINCONV_TYPE_TEMPLATESIZE_256
        MINCONV_TYPE_TEMPLATESIZE_272
        MINCONV_TYPE_TEMPLATESIZE_288
        MINCONV_TYPE_TEMPLATESIZE_304
        MINCONV_TYPE_TEMPLATESIZE_320
        MINCONV_TYPE_TEMPLATESIZE_336
        MINCONV_TYPE_TEMPLATESIZE_352
        MINCONV_TYPE_TEMPLATESIZE_368
        MINCONV_TYPE_TEMPLATESIZE_384
        MINCONV_TYPE_TEMPLATESIZE_400
        MINCONV_TYPE_ANSI
        MINCONV_TYPE_ISO
        MINCONV_TYPE_MAX

    ctypedef NBioAPI_UINT8 NBioAPI_FINGER_ID

    cdef struct nbioapi_match_option_0:
        NBioAPI_UINT8 StructureType
        NBioAPI_UINT8 NoMatchFinger[11]
        NBioAPI_UINT32 Reserved[8]

    ctypedef nbioapi_match_option_0 NBioAPI_MATCH_OPTION_0

    ctypedef nbioapi_match_option_0 *NBioAPI_MATCH_OPTION_PTR_0

    ctypedef NBioAPI_VOID_PTR NBioAPI_MATCH_OPTION_PTR

    ctypedef NBioAPI_UINT8 NBioAPI_QUALITY

    cdef struct nbioapi_quality_info_0:
        NBioAPI_UINT8 StructureType
        NBioAPI_QUALITY Quality[11][2]
        NBioAPI_UINT32 Reserved[4]

    ctypedef nbioapi_quality_info_0 NBioAPI_QUALITY_INFO_0

    ctypedef nbioapi_quality_info_0 *NBioAPI_QUALITY_INFO_PTR_0

    cdef struct nbioapi_quality_info_1:
        NBioAPI_UINT8 StructureType
        NBioAPI_UINT8 Quality[11][2]
        NBioAPI_UINT32 Reserved[4]

    ctypedef nbioapi_quality_info_1 NBioAPI_QUALITY_INFO_1

    ctypedef nbioapi_quality_info_1 *NBioAPI_QUALITY_INFO_PTR_1

    ctypedef NBioAPI_VOID_PTR NBioAPI_QUALITY_INFO_PTR

    cdef struct nbioapi_deviceinfoex:
        NBioAPI_DEVICE_ID NameID
        NBioAPI_UINT16 Instance
        NBioAPI_CHAR Name[64]
        NBioAPI_CHAR Description[256]
        NBioAPI_CHAR Dll[64]
        NBioAPI_CHAR Sys[64]
        NBioAPI_UINT32 AutoOn
        NBioAPI_UINT32 Brightness
        NBioAPI_UINT32 Contrast
        NBioAPI_UINT32 Gain
        NBioAPI_UINT32 Reserved[8]

    ctypedef nbioapi_deviceinfoex NBioAPI_DEVICE_INFO_EX

    ctypedef nbioapi_deviceinfoex *NBioAPI_DEVICE_INFO_EX_PTR

    cdef NBioAPI_RETURN NBioAPI_Init(NBioAPI_HANDLE_PTR phHandle)

    cdef NBioAPI_RETURN NBioAPI_Terminate(NBioAPI_HANDLE hHandle)

    cdef NBioAPI_RETURN NBioAPI_GetValidityCode(NBioAPI_HANDLE hHandle, NBioAPI_UINT32 Code1, NBioAPI_UINT32 Code2, NBioAPI_UINT32 Code3, NBioAPI_UINT32 Code4, NBioAPI_UINT32 *pResult1, NBioAPI_UINT32 *pResult2)

    cdef NBioAPI_RETURN NBioAPI_GetVersion(NBioAPI_HANDLE hHandle, NBioAPI_VERSION_PTR pVersion)

    cdef NBioAPI_RETURN NBioAPI_GetInitInfo(NBioAPI_HANDLE hHandle, NBioAPI_UINT8 nStructureType, NBioAPI_INIT_INFO_PTR pInitInfo)

    cdef NBioAPI_RETURN NBioAPI_SetInitInfo(NBioAPI_HANDLE hHandle, NBioAPI_UINT8 nStructureType, NBioAPI_INIT_INFO_PTR pInitInfo)

    cdef NBioAPI_RETURN NBioAPI_EnumerateDevice(NBioAPI_HANDLE hHandle, NBioAPI_UINT32 *pNumDevice, NBioAPI_DEVICE_ID **ppDeviceID)

    cdef NBioAPI_RETURN NBioAPI_EnumerateDeviceEx(NBioAPI_HANDLE hHandle, NBioAPI_UINT32 *pNumDevice, NBioAPI_DEVICE_ID **ppDeviceID, NBioAPI_DEVICE_INFO_EX **ppDeviceInfoEx)

    cdef NBioAPI_RETURN NBioAPI_OpenDevice(NBioAPI_HANDLE hHandle, NBioAPI_DEVICE_ID nDeviceID)

    cdef NBioAPI_RETURN NBioAPI_CloseDevice(NBioAPI_HANDLE hHandle, NBioAPI_DEVICE_ID nDeviceID)

    cdef NBioAPI_RETURN NBioAPI_GetDeviceInfo(NBioAPI_HANDLE hHandle, NBioAPI_DEVICE_ID nDeviceID, NBioAPI_UINT8 nStructureType, NBioAPI_DEVICE_INFO_PTR pDeviceInfo)

    cdef NBioAPI_RETURN NBioAPI_SetDeviceInfo(NBioAPI_HANDLE hHandle, NBioAPI_DEVICE_ID nDeviceID, NBioAPI_UINT8 nStructureType, NBioAPI_DEVICE_INFO_PTR pDeviceInfo)

    cdef NBioAPI_RETURN NBioAPI_AdjustDevice(NBioAPI_HANDLE hHandle, const NBioAPI_WINDOW_OPTION_PTR pWindowOption)

    cdef NBioAPI_DEVICE_ID NBioAPI_GetOpenedDeviceID(NBioAPI_HANDLE hHandle)

    cdef NBioAPI_RETURN NBioAPI_FreeFIRHandle(NBioAPI_HANDLE hHandle, NBioAPI_FIR_HANDLE hFIR)

    cdef NBioAPI_RETURN NBioAPI_GetFIRFromHandle(NBioAPI_HANDLE hHandle, NBioAPI_FIR_HANDLE hFIR, NBioAPI_FIR_PTR pFIR)

    cdef NBioAPI_RETURN NBioAPI_GetHeaderFromHandle(NBioAPI_HANDLE hHandle, NBioAPI_FIR_HANDLE hFIR, NBioAPI_FIR_HEADER_PTR pHeader)

    cdef NBioAPI_RETURN NBioAPI_GetExtendedFIRFromHandle(NBioAPI_HANDLE hHandle, NBioAPI_FIR_HANDLE hFIR, NBioAPI_VOID_PTR pFIR, NBioAPI_FIR_FORMAT Format)

    cdef NBioAPI_RETURN NBioAPI_GetExtendedHeaderFromHandle(NBioAPI_HANDLE hHandle, NBioAPI_FIR_HANDLE hFIR, NBioAPI_VOID_PTR pHeader, NBioAPI_FIR_FORMAT Format)

    cdef NBioAPI_RETURN NBioAPI_FreeFIR(NBioAPI_HANDLE hHandle, NBioAPI_VOID_PTR pFIR)

    cdef NBioAPI_RETURN NBioAPI_FreePayload(NBioAPI_HANDLE hHandle, NBioAPI_FIR_PAYLOAD_PTR pPayload)

    cdef NBioAPI_RETURN NBioAPI_GetTextFIRFromHandle(NBioAPI_HANDLE hHandle, NBioAPI_FIR_HANDLE hFIR, NBioAPI_FIR_TEXTENCODE_PTR pTextFIR, NBioAPI_BOOL bIsWide)

    cdef NBioAPI_RETURN NBioAPI_GetExtendedTextFIRFromHandle(NBioAPI_HANDLE hHandle, NBioAPI_FIR_HANDLE hFIR, NBioAPI_FIR_TEXTENCODE_PTR pTextFIR, NBioAPI_BOOL bIsWide, NBioAPI_FIR_FORMAT Format)

    cdef NBioAPI_RETURN NBioAPI_FreeTextFIR(NBioAPI_HANDLE hHandle, NBioAPI_FIR_TEXTENCODE_PTR pTextFIR)

    cdef NBioAPI_RETURN NBioAPI_Capture(NBioAPI_HANDLE hHandle, NBioAPI_FIR_PURPOSE nPurpose, NBioAPI_FIR_HANDLE_PTR phCapturedFIR, NBioAPI_SINT32 nTimeout, NBioAPI_FIR_HANDLE_PTR phAuditData, const NBioAPI_WINDOW_OPTION_PTR pWindowOption)

    cdef NBioAPI_RETURN NBioAPI_Process(NBioAPI_HANDLE hHandle, const NBioAPI_INPUT_FIR_PTR piCapturedFIR, NBioAPI_FIR_HANDLE_PTR phProcessedFIR)

    cdef NBioAPI_RETURN NBioAPI_CreateTemplate(NBioAPI_HANDLE hHandle, const NBioAPI_INPUT_FIR_PTR piCapturedFIR, const NBioAPI_INPUT_FIR_PTR piStoredTemplate, NBioAPI_FIR_HANDLE_PTR phNewTemplate, const NBioAPI_FIR_PAYLOAD_PTR pPayload)

    cdef NBioAPI_RETURN NBioAPI_VerifyMatch(NBioAPI_HANDLE hHandle, const NBioAPI_INPUT_FIR_PTR piProcessedFIR, const NBioAPI_INPUT_FIR_PTR piStoredTemplate, NBioAPI_BOOL *pbResult, NBioAPI_FIR_PAYLOAD_PTR pPayload)

    cdef NBioAPI_RETURN NBioAPI_VerifyMatchEx(NBioAPI_HANDLE hHandle, const NBioAPI_INPUT_FIR_PTR piProcessedFIR, const NBioAPI_INPUT_FIR_PTR piStoredTemplate, NBioAPI_BOOL *pbResult, NBioAPI_FIR_PAYLOAD_PTR pPayload, NBioAPI_MATCH_OPTION_PTR pMatchOption)

    cdef NBioAPI_RETURN NBioAPI_Enroll(NBioAPI_HANDLE hHandle, const NBioAPI_INPUT_FIR_PTR piStoredTemplate, NBioAPI_FIR_HANDLE_PTR phNewTemplate, const NBioAPI_FIR_PAYLOAD_PTR pPayload, NBioAPI_SINT32 nTimeout, NBioAPI_FIR_HANDLE_PTR phAuditData, const NBioAPI_WINDOW_OPTION_PTR pWindowOption)

    cdef NBioAPI_RETURN NBioAPI_Verify(NBioAPI_HANDLE hHandle, const NBioAPI_INPUT_FIR_PTR piStoredTemplate, NBioAPI_BOOL *pbResult, NBioAPI_FIR_PAYLOAD_PTR pPayload, NBioAPI_SINT32 nTimeout, NBioAPI_FIR_HANDLE_PTR phAuditData, const NBioAPI_WINDOW_OPTION_PTR pWindowOption)

    cdef NBioAPI_RETURN NBioAPI_CheckFinger(NBioAPI_HANDLE hHandle, NBioAPI_BOOL *bFingerExist)

    cdef NBioAPI_RETURN NBioAPI_GetQualityInfo(NBioAPI_HANDLE hHandle, const NBioAPI_INPUT_FIR_PTR pAuditData, const NBioAPI_INPUT_FIR_PTR pFIR, NBioAPI_UINT8 nStructureType, NBioAPI_QUALITY_INFO_PTR pQualityInfo)

    cdef NBioAPI_RETURN NBioAPI_RollCapture(NBioAPI_HANDLE hHandle, NBioAPI_FIR_PURPOSE nPurpose, NBioAPI_SINT32 nTimeout, NBioAPI_FIR_HANDLE_PTR phCapturedFIR, NBioAPI_FIR_HANDLE_PTR phAuditData, const NBioAPI_WINDOW_OPTION_PTR pWindowOption)



    ctypedef unsigned int (*FP_NBioAPI_Init)(unsigned int *)

    ctypedef unsigned int (*FP_NBioAPI_Terminate)(unsigned int)

    ctypedef unsigned int (*FP_NBioAPI_GetValidityCode)(unsigned int, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int *, unsigned int *)

    ctypedef unsigned int (*FP_NBioAPI_GetVersion)(unsigned int, nbioapi_version *)

    ctypedef unsigned int (*FP_NBioAPI_GetInitInfo)(unsigned int, unsigned char, void *)

    ctypedef unsigned int (*FP_NBioAPI_SetInitInfo)(unsigned int, unsigned char, void *)

    ctypedef unsigned int (*FP_NBioAPI_EnumerateDevice)(unsigned int, unsigned int *, unsigned short **)

    ctypedef unsigned int (*FP_NBioAPI_EnumerateDeviceEx)(unsigned int, unsigned int *, unsigned short **, nbioapi_deviceinfoex **)

    ctypedef unsigned int (*FP_NBioAPI_OpenDevice)(unsigned int, unsigned short)

    ctypedef unsigned int (*FP_NBioAPI_CloseDevice)(unsigned int, unsigned short)

    ctypedef unsigned int (*FP_NBioAPI_GetDeviceInfo)(unsigned int, unsigned short, unsigned char, void *)

    ctypedef unsigned int (*FP_NBioAPI_SetDeviceInfo)(unsigned int, unsigned short, unsigned char, void *)

    ctypedef unsigned int (*FP_NBioAPI_AdjustDevice)(unsigned int, nbioapi_window_option *)

    ctypedef unsigned short (*FP_NBioAPI_GetOpenedDeviceID)(unsigned int)

    ctypedef unsigned int (*FP_NBioAPI_FreeFIRHandle)(unsigned int, unsigned int)

    ctypedef unsigned int (*FP_NBioAPI_GetFIRFromHandle)(unsigned int, unsigned int, nbioapi_fir *)

    ctypedef unsigned int (*FP_NBioAPI_GetHeaderFromHandle)(unsigned int, unsigned int, nbioapi_fir_header *)

    ctypedef unsigned int (*FP_NBioAPI_GetExtendedFIRFromHandle)(unsigned int, unsigned int, void *, unsigned int)

    ctypedef unsigned int (*FP_NBioAPI_GetExtendedHeaderFromHandle)(unsigned int, unsigned int, void *, unsigned int)

    ctypedef unsigned int (*FP_NBioAPI_FreeFIR)(unsigned int, void *)

    ctypedef unsigned int (*FP_NBioAPI_FreePayload)(unsigned int, nbioapi_fir_payload *)

    ctypedef unsigned int (*FP_NBioAPI_GetTextFIRFromHandle)(unsigned int, unsigned int, nbioapi_fir_textencode *, int)

    ctypedef unsigned int (*FP_NBioAPI_GetExtendedTextFIRFromHandle)(unsigned int, unsigned int, nbioapi_fir_textencode *, int, unsigned int)

    ctypedef unsigned int (*FP_NBioAPI_FreeTextFIR)(unsigned int, nbioapi_fir_textencode *)

    ctypedef unsigned int (*FP_NBioAPI_Capture)(unsigned int, unsigned short, unsigned int *, int, unsigned int *, nbioapi_window_option *)

    ctypedef unsigned int (*FP_NBioAPI_Process)(unsigned int, nbioapi_input_fir *, unsigned int *)

    ctypedef unsigned int (*FP_NBioAPI_CreateTemplate)(unsigned int, nbioapi_input_fir *, nbioapi_input_fir *, unsigned int *, nbioapi_fir_payload *)

    ctypedef unsigned int (*FP_NBioAPI_VerifyMatch)(unsigned int, nbioapi_input_fir *, nbioapi_input_fir *, int *, nbioapi_fir_payload *)

    ctypedef unsigned int (*FP_NBioAPI_VerifyMatchEx)(unsigned int, nbioapi_input_fir *, nbioapi_input_fir *, int *, nbioapi_fir_payload *, void *)

    ctypedef unsigned int (*FP_NBioAPI_Enroll)(unsigned int, nbioapi_input_fir *, unsigned int *, nbioapi_fir_payload *, int, unsigned int *, nbioapi_window_option *)

    ctypedef unsigned int (*FP_NBioAPI_Verify)(unsigned int, nbioapi_input_fir *, int *, nbioapi_fir_payload *, int, unsigned int *, nbioapi_window_option *)

    ctypedef unsigned int (*FP_NBioAPI_CheckFinger)(unsigned int, int *)

    ctypedef unsigned int (*FP_NBioAPI_GetQualityInfo)(unsigned int, nbioapi_input_fir *, nbioapi_input_fir *, unsigned char, void *)

    ctypedef unsigned int (*FP_NBioAPI_RollCapture)(unsigned int, unsigned short, int, unsigned int *, unsigned int *, nbioapi_window_option *)


def iniciar():
    cdef NBioAPI_HANDLE_PTR ret
    a = NBioAPI_Init(ret)
    return a
